name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile without solutions
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: cs141-summer19.tex
          args: -bibtex -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape -latexoption=-synctex=1

      - name: Upload build artifact (without solutions)
        uses: actions/upload-artifact@v2
        with:
          name: cs141-summer19.pdf
          path: cs141-summer19.pdf

      - name: Compile with solutions
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: cs141-summer19-solutions.tex
          args: -bibtex -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape -latexoption=-synctex=1

      - name: Upload build artifact (with solutions)
        uses: actions/upload-artifact@v2
        with:
          name: cs141-summer19-solutions.pdf
          path: cs141-summer19-solutions.pdf
